# Generated by Django 5.0.2 on 2024-02-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api_root', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authusermodel',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='authusermodel',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='authusermodel',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='authusermodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
